
server:
  port: 8888



spring:
  application:
    name: config-service
#
#  profiles:
#    active: native
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: file://${user.home}/Desk



  cloud:
    config:
      server:
        git:
          uri: file:///Users/for/Desktop/minwoofile/infrun MSA/spring cloud config
          ## uri: 깃주소
          ## private 일 경우
          ##username: [your name]
          ##password: [your password]